/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Gstreamer */

#ifndef _Included_jni_Gstreamer
#define _Included_jni_Gstreamer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Gstreamer
 * Method:    initCam
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jni_Gstreamer_initCam
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jni_Gstreamer
 * Method:    readMat
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_jni_Gstreamer_readMat
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     jni_Gstreamer
 * Method:    releaseCam
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jni_Gstreamer_releaseCam
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
