syntax = "proto3";

package photonvision.core.proto;


// List of all the changes that can be requested
message SetDriverMode {
    bool isDriverMode = 1;
}


// UI -> Frontend format
message VisionModuleEvent {
    string cameraUniqueName = 1;

    oneof event {
        SetDriverMode driverMode = 2;
    }
}

message UiChangeEvent {
    oneof event {
        VisionModuleEvent vm_change = 1;
        // TODO none-VM-specific change messages
    }
}

// Only created by backend
message PhotonDataChangeEvent {
    // Websocket session this request came from
    string originCtxSessionId = 1;

    UiChangeEvent event = 2;
}

