// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               v7.36.2
// source: PhotonMessage.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "photonvision.core.proto";

/** UI -> Frontend format */
export interface VisionModuleEvent {
  cameraUniqueName: string;
  driverMode?: boolean | undefined;
}

export interface UiChangeEvent {
  /** TODO none-VM-specific change messages */
  vmChange?: VisionModuleEvent | undefined;
}

/** Only created by backend */
export interface PhotonDataChangeEvent {
  /** Websocket session this request came from */
  originCtxSessionId: string;
  event: UiChangeEvent | undefined;
}

function createBaseVisionModuleEvent(): VisionModuleEvent {
  return { cameraUniqueName: "", driverMode: undefined };
}

export const VisionModuleEvent: MessageFns<VisionModuleEvent> = {
  encode(message: VisionModuleEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cameraUniqueName !== "") {
      writer.uint32(10).string(message.cameraUniqueName);
    }
    if (message.driverMode !== undefined) {
      writer.uint32(16).bool(message.driverMode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VisionModuleEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseVisionModuleEvent();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.cameraUniqueName = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.driverMode = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): VisionModuleEvent {
    return {
      cameraUniqueName: isSet(object.cameraUniqueName) ? globalThis.String(object.cameraUniqueName) : "",
      driverMode: isSet(object.driverMode) ? globalThis.Boolean(object.driverMode) : undefined,
    };
  },

  toJSON(message: VisionModuleEvent): unknown {
    const obj: any = {};
    if (message.cameraUniqueName !== "") {
      obj.cameraUniqueName = message.cameraUniqueName;
    }
    if (message.driverMode !== undefined) {
      obj.driverMode = message.driverMode;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VisionModuleEvent>, I>>(base?: I): VisionModuleEvent {
    return VisionModuleEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VisionModuleEvent>, I>>(object: I): VisionModuleEvent {
    const message = createBaseVisionModuleEvent();
    message.cameraUniqueName = object.cameraUniqueName ?? "";
    message.driverMode = object.driverMode ?? undefined;
    return message;
  },
};

function createBaseUiChangeEvent(): UiChangeEvent {
  return { vmChange: undefined };
}

export const UiChangeEvent: MessageFns<UiChangeEvent> = {
  encode(message: UiChangeEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.vmChange !== undefined) {
      VisionModuleEvent.encode(message.vmChange, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UiChangeEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseUiChangeEvent();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.vmChange = VisionModuleEvent.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): UiChangeEvent {
    return {
      vmChange: isSet(object.vmChange)
        ? VisionModuleEvent.fromJSON(object.vmChange)
        : isSet(object.vm_change)
        ? VisionModuleEvent.fromJSON(object.vm_change)
        : undefined,
    };
  },

  toJSON(message: UiChangeEvent): unknown {
    const obj: any = {};
    if (message.vmChange !== undefined) {
      obj.vmChange = VisionModuleEvent.toJSON(message.vmChange);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UiChangeEvent>, I>>(base?: I): UiChangeEvent {
    return UiChangeEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UiChangeEvent>, I>>(object: I): UiChangeEvent {
    const message = createBaseUiChangeEvent();
    message.vmChange = (object.vmChange !== undefined && object.vmChange !== null)
      ? VisionModuleEvent.fromPartial(object.vmChange)
      : undefined;
    return message;
  },
};

function createBasePhotonDataChangeEvent(): PhotonDataChangeEvent {
  return { originCtxSessionId: "", event: undefined };
}

export const PhotonDataChangeEvent: MessageFns<PhotonDataChangeEvent> = {
  encode(message: PhotonDataChangeEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.originCtxSessionId !== "") {
      writer.uint32(10).string(message.originCtxSessionId);
    }
    if (message.event !== undefined) {
      UiChangeEvent.encode(message.event, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PhotonDataChangeEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePhotonDataChangeEvent();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.originCtxSessionId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.event = UiChangeEvent.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): PhotonDataChangeEvent {
    return {
      originCtxSessionId: isSet(object.originCtxSessionId) ? globalThis.String(object.originCtxSessionId) : "",
      event: isSet(object.event) ? UiChangeEvent.fromJSON(object.event) : undefined,
    };
  },

  toJSON(message: PhotonDataChangeEvent): unknown {
    const obj: any = {};
    if (message.originCtxSessionId !== "") {
      obj.originCtxSessionId = message.originCtxSessionId;
    }
    if (message.event !== undefined) {
      obj.event = UiChangeEvent.toJSON(message.event);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PhotonDataChangeEvent>, I>>(base?: I): PhotonDataChangeEvent {
    return PhotonDataChangeEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PhotonDataChangeEvent>, I>>(object: I): PhotonDataChangeEvent {
    const message = createBasePhotonDataChangeEvent();
    message.originCtxSessionId = object.originCtxSessionId ?? "";
    message.event = (object.event !== undefined && object.event !== null)
      ? UiChangeEvent.fromPartial(object.event)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
