/*
 * Copyright (C) Photon Vision.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// THIS FILE WAS AUTO-GENERATED BY ./photon-serde/generate_messages.py. DO NOT MODIFY

package org.photonvision;

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import org.photonvision.common.dataflow.structures.Packet;
import org.photonvision.targeting.*;
import org.photonvision.targeting.serde.PhotonStructSerializable;

import org.wpilib.math.geometry.Rotation3d;
import org.wpilib.math.geometry.Translation3d;
import org.wpilib.math.geometry.Transform3d;


public class AutoSerdeTest {
    private <T extends PhotonStructSerializable<T>> boolean testSerde(T data) {
        var p = new Packet(10);
        p.encode(data);
        var unpackedData = p.decode(data); // kinda scuffed lowkey
        System.out.println("IN: " + data.toString() + "\nOUT: " + unpackedData.toString());
        return data.equals(unpackedData);
    }
    
    @Test
    public void Int8Test() {
        System.out.println("Running Int8Test");
        
        var default_test = new Int8TestMessage();
        assertTrue(testSerde(default_test));
        
        var optional_test = new Int8TestMessage();
        optional_test.optTest = Optional.of((byte) 3);
        assertTrue(testSerde(optional_test));
        
        var vla_test = new Int8TestMessage();
        vla_test.vlaTest = List.of((byte) 1, (byte) 2, (byte) 3);
        assertTrue(testSerde(vla_test));
        
        var general_test = new Int8TestMessage();
        general_test.test = (byte) 42;
        general_test.optTest = Optional.of((byte) 7);
        general_test.vlaTest = List.of((byte) 4, (byte) 5, (byte) 6);
        assertTrue(testSerde(general_test));
        
    }
    
    @Test
    public void Int16Test() {
        System.out.println("Running Int16Test");
        
        var default_test = new Int16TestMessage();
        assertTrue(testSerde(default_test));
        
        var optional_test = new Int16TestMessage();
        optional_test.optTest = Optional.of((short) 3);
        assertTrue(testSerde(optional_test));
        
        var vla_test = new Int16TestMessage();
        vla_test.vlaTest = List.of((short) 1, (short) 2, (short) 3);
        assertTrue(testSerde(vla_test));
        
        var general_test = new Int16TestMessage();
        general_test.test = (short) 42;
        general_test.optTest = Optional.of((short) 7);
        general_test.vlaTest = List.of((short) 4, (short) 5, (short) 6);
        assertTrue(testSerde(general_test));
        
    }
    
    @Test
    public void Int32Test() {
        System.out.println("Running Int32Test");
        
        var default_test = new Int32TestMessage();
        assertTrue(testSerde(default_test));
        
        var optional_test = new Int32TestMessage();
        optional_test.optTest = Optional.of((int) 3);
        assertTrue(testSerde(optional_test));
        
        var vla_test = new Int32TestMessage();
        vla_test.vlaTest = List.of((int) 1, (int) 2, (int) 3);
        assertTrue(testSerde(vla_test));
        
        var general_test = new Int32TestMessage();
        general_test.test = (int) 42;
        general_test.optTest = Optional.of((int) 7);
        general_test.vlaTest = List.of((int) 4, (int) 5, (int) 6);
        assertTrue(testSerde(general_test));
        
    }
    
    @Test
    public void Int64Test() {
        System.out.println("Running Int64Test");
        
        var default_test = new Int64TestMessage();
        assertTrue(testSerde(default_test));
        
        var optional_test = new Int64TestMessage();
        optional_test.optTest = Optional.of((long) 3);
        assertTrue(testSerde(optional_test));
        
        var vla_test = new Int64TestMessage();
        vla_test.vlaTest = List.of((long) 1, (long) 2, (long) 3);
        assertTrue(testSerde(vla_test));
        
        var general_test = new Int64TestMessage();
        general_test.test = (long) 42;
        general_test.optTest = Optional.of((long) 7);
        general_test.vlaTest = List.of((long) 4, (long) 5, (long) 6);
        assertTrue(testSerde(general_test));
        
    }
    
    @Test
    public void Float32Test() {
        System.out.println("Running Float32Test");
        
        var default_test = new Float32TestMessage();
        assertTrue(testSerde(default_test));
        
        var optional_test = new Float32TestMessage();
        optional_test.optTest = Optional.of((float) 3.0);
        assertTrue(testSerde(optional_test));
        
        var vla_test = new Float32TestMessage();
        vla_test.vlaTest = List.of((float) 1.0, (float) 2.0, (float) 3.0);
        assertTrue(testSerde(vla_test));
        
        var general_test = new Float32TestMessage();
        general_test.test = (float) 42.0;
        general_test.optTest = Optional.of((float) 7.0);
        general_test.vlaTest = List.of((float) 4.0, (float) 5.0, (float) 6.0);
        assertTrue(testSerde(general_test));
        
    }
    
    @Test
    public void Float64Test() {
        System.out.println("Running Float64Test");
        
        var default_test = new Float64TestMessage();
        assertTrue(testSerde(default_test));
        
        var optional_test = new Float64TestMessage();
        optional_test.optTest = Optional.of((double) 3.0);
        assertTrue(testSerde(optional_test));
        
        var vla_test = new Float64TestMessage();
        vla_test.vlaTest = List.of((double) 1.0, (double) 2.0, (double) 3.0);
        assertTrue(testSerde(vla_test));
        
        var general_test = new Float64TestMessage();
        general_test.test = (double) 42.0;
        general_test.optTest = Optional.of((double) 7.0);
        general_test.vlaTest = List.of((double) 4.0, (double) 5.0, (double) 6.0);
        assertTrue(testSerde(general_test));
        
    }
    
    @Test
    public void BoolTest() {
        System.out.println("Running BoolTest");
        
        var default_test = new BoolTestMessage();
        assertTrue(testSerde(default_test));
        
        var optional_test = new BoolTestMessage();
        optional_test.optTest = Optional.of(true);
        assertTrue(testSerde(optional_test));
        
        var vla_test = new BoolTestMessage();
        vla_test.vlaTest = List.of(true, false, true);
        assertTrue(testSerde(vla_test));
        
        var general_test = new BoolTestMessage();
        general_test.test = false;
        general_test.optTest = Optional.of(true);
        general_test.vlaTest = List.of(true, false, true);
        assertTrue(testSerde(general_test));
        
    }
    
    @Test
    public void Transform3dTest() {
        System.out.println("Running Transform3dTest");
        
        var default_test = new Transform3dTestMessage();
        assertTrue(testSerde(default_test));
        
        var optional_test = new Transform3dTestMessage();
        optional_test.optTest = Optional.of(new Transform3d(new Translation3d(1.0, 2.0, 3.0), new Rotation3d(0.1, 0.2, 0.3)));
        assertTrue(testSerde(optional_test));
        
        var vla_test = new Transform3dTestMessage();
        vla_test.vlaTest = List.of(new Transform3d(new Translation3d(1.0, 2.0, 3.0), new Rotation3d(0.1, 0.2, 0.3)), new Transform3d(new Translation3d(4.0, 5.0, 6.0), new Rotation3d(0.4, 0.5, 0.6)));
        assertTrue(testSerde(vla_test));
        
        var general_test = new Transform3dTestMessage();
        general_test.test = new Transform3d(new Translation3d(7.0, 8.0, 9.0), new Rotation3d(0.7, 0.8, 0.9));
        general_test.optTest = Optional.of(new Transform3d(new Translation3d(1.0, 2.0, 3.0), new Rotation3d(0.1, 0.2, 0.3)));
        general_test.vlaTest = List.of(new Transform3d(new Translation3d(1.0, 2.0, 3.0), new Rotation3d(0.1, 0.2, 0.3)), new Transform3d(new Translation3d(4.0, 5.0, 6.0), new Rotation3d(0.4, 0.5, 0.6)));
        assertTrue(testSerde(general_test));
        
    }
    
}