/*
 * Copyright (C) Photon Vision.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// THIS FILE WAS AUTO-GENERATED BY ./photon-serde/generate_messages.py. DO NOT MODIFY

#include <iostream>
#include <optional>
#include <vector>

#include <wpi/hal/HAL.h>

#include "gtest/gtest.h"

#include <wpi/math/geometry/Rotation3d.hpp>
#include <wpi/math/geometry/Translation3d.hpp>
#include <wpi/math/geometry/Transform3d.hpp>
#include <wpi/units/angle.hpp>


#include "photon/targeting/Int8TestMessage.h"
#include "photon/targeting/Int16TestMessage.h"
#include "photon/targeting/Int32TestMessage.h"
#include "photon/targeting/Int64TestMessage.h"
#include "photon/targeting/Float32TestMessage.h"
#include "photon/targeting/Float64TestMessage.h"
#include "photon/targeting/BoolTestMessage.h"
#include "photon/targeting/Transform3dTestMessage.h"


// Hack
int main(int argc, char** argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}

using namespace photon;

template <typename T>
  requires(PhotonStructSerializable<T>)
inline bool test_serde(const T& data) {
  Packet p;
  p.Pack<T>(data);
  T unpackedData = p.Unpack<T>();
  return data == unpackedData;
}


TEST(AutoSerdeTest, Int8Test) {
    std::cout << "Running Int8Test\n";
    
    Int8TestMessage default_test{};
    ASSERT_TRUE(test_serde(default_test));
    
    Int8TestMessage optional_test{};
    optional_test.optTest = {3};
    ASSERT_TRUE(test_serde(optional_test));
    
    Int8TestMessage vla_test{};
    vla_test.vlaTest = {1, 2, 3};
    ASSERT_TRUE(test_serde(vla_test));
    
    Int8TestMessage general_test{};
    general_test.test = 42;
    general_test.optTest = {7};
    general_test.vlaTest = {4, 5, 6};
    ASSERT_TRUE(test_serde(general_test));
    
}

TEST(AutoSerdeTest, Int16Test) {
    std::cout << "Running Int16Test\n";
    
    Int16TestMessage default_test{};
    ASSERT_TRUE(test_serde(default_test));
    
    Int16TestMessage optional_test{};
    optional_test.optTest = {3};
    ASSERT_TRUE(test_serde(optional_test));
    
    Int16TestMessage vla_test{};
    vla_test.vlaTest = {1, 2, 3};
    ASSERT_TRUE(test_serde(vla_test));
    
    Int16TestMessage general_test{};
    general_test.test = 42;
    general_test.optTest = {7};
    general_test.vlaTest = {4, 5, 6};
    ASSERT_TRUE(test_serde(general_test));
    
}

TEST(AutoSerdeTest, Int32Test) {
    std::cout << "Running Int32Test\n";
    
    Int32TestMessage default_test{};
    ASSERT_TRUE(test_serde(default_test));
    
    Int32TestMessage optional_test{};
    optional_test.optTest = {3};
    ASSERT_TRUE(test_serde(optional_test));
    
    Int32TestMessage vla_test{};
    vla_test.vlaTest = {1, 2, 3};
    ASSERT_TRUE(test_serde(vla_test));
    
    Int32TestMessage general_test{};
    general_test.test = 42;
    general_test.optTest = {7};
    general_test.vlaTest = {4, 5, 6};
    ASSERT_TRUE(test_serde(general_test));
    
}

TEST(AutoSerdeTest, Int64Test) {
    std::cout << "Running Int64Test\n";
    
    Int64TestMessage default_test{};
    ASSERT_TRUE(test_serde(default_test));
    
    Int64TestMessage optional_test{};
    optional_test.optTest = {3};
    ASSERT_TRUE(test_serde(optional_test));
    
    Int64TestMessage vla_test{};
    vla_test.vlaTest = {1, 2, 3};
    ASSERT_TRUE(test_serde(vla_test));
    
    Int64TestMessage general_test{};
    general_test.test = 42;
    general_test.optTest = {7};
    general_test.vlaTest = {4, 5, 6};
    ASSERT_TRUE(test_serde(general_test));
    
}

TEST(AutoSerdeTest, Float32Test) {
    std::cout << "Running Float32Test\n";
    
    Float32TestMessage default_test{};
    ASSERT_TRUE(test_serde(default_test));
    
    Float32TestMessage optional_test{};
    optional_test.optTest = {3.0};
    ASSERT_TRUE(test_serde(optional_test));
    
    Float32TestMessage vla_test{};
    vla_test.vlaTest = {1.0, 2.0, 3.0};
    ASSERT_TRUE(test_serde(vla_test));
    
    Float32TestMessage general_test{};
    general_test.test = 42.0;
    general_test.optTest = {7.0};
    general_test.vlaTest = {4.0, 5.0, 6.0};
    ASSERT_TRUE(test_serde(general_test));
    
}

TEST(AutoSerdeTest, Float64Test) {
    std::cout << "Running Float64Test\n";
    
    Float64TestMessage default_test{};
    ASSERT_TRUE(test_serde(default_test));
    
    Float64TestMessage optional_test{};
    optional_test.optTest = {3.0};
    ASSERT_TRUE(test_serde(optional_test));
    
    Float64TestMessage vla_test{};
    vla_test.vlaTest = {1.0, 2.0, 3.0};
    ASSERT_TRUE(test_serde(vla_test));
    
    Float64TestMessage general_test{};
    general_test.test = 42.0;
    general_test.optTest = {7.0};
    general_test.vlaTest = {4.0, 5.0, 6.0};
    ASSERT_TRUE(test_serde(general_test));
    
}

TEST(AutoSerdeTest, BoolTest) {
    std::cout << "Running BoolTest\n";
    
    BoolTestMessage default_test{};
    ASSERT_TRUE(test_serde(default_test));
    
    BoolTestMessage optional_test{};
    optional_test.optTest = {true};
    ASSERT_TRUE(test_serde(optional_test));
    
    BoolTestMessage vla_test{};
    vla_test.vlaTest = {true, false, true};
    ASSERT_TRUE(test_serde(vla_test));
    
    BoolTestMessage general_test{};
    general_test.test = false;
    general_test.optTest = {true};
    general_test.vlaTest = {true, false, true};
    ASSERT_TRUE(test_serde(general_test));
    
}

TEST(AutoSerdeTest, Transform3dTest) {
    std::cout << "Running Transform3dTest\n";
    
    Transform3dTestMessage default_test{};
    ASSERT_TRUE(test_serde(default_test));
    
    Transform3dTestMessage optional_test{};
    optional_test.optTest = {1_m, 2_m, 3_m, wpi::math::Rotation3d{6_deg, 7_deg, 12_deg}};
    ASSERT_TRUE(test_serde(optional_test));
    
    Transform3dTestMessage vla_test{};
    vla_test.vlaTest = {{1_m, 2_m, 3_m, wpi::math::Rotation3d{6_deg, 7_deg, 12_deg}},{1_m, 2_m, 3_m, wpi::math::Rotation3d{6_deg, 7_deg, 12_deg}},{8_m, 2_m, 1_m, wpi::math::Rotation3d{0_deg, 1_deg, 88_deg}}};
    ASSERT_TRUE(test_serde(vla_test));
    
    Transform3dTestMessage general_test{};
    general_test.test = {8_m, 2_m, 1_m, wpi::math::Rotation3d{0_deg, 1_deg, 88_deg}};
    general_test.optTest = {1_m, 2_m, 3_m, wpi::math::Rotation3d{6_deg, 7_deg, 12_deg}};
    general_test.vlaTest = {{1_m, 2_m, 3_m, wpi::math::Rotation3d{6_deg, 7_deg, 12_deg}},{1_m, 2_m, 3_m, wpi::math::Rotation3d{6_deg, 7_deg, 12_deg}},{8_m, 2_m, 1_m, wpi::math::Rotation3d{0_deg, 1_deg, 88_deg}}};
    ASSERT_TRUE(test_serde(general_test));
    
}
