/*
 * MIT License
 *
 * Copyright (c) PhotonVision
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// THIS FILE WAS AUTO-GENERATED BY ./photon-serde/generate_messages.py. DO NOT MODIFY

package org.photonvision.struct;

import org.photonvision.common.dataflow.structures.Packet;
import org.photonvision.common.dataflow.structures.PacketSerde;
import org.photonvision.utils.PacketUtils;

// Assume that the base class lives here and we can import it
import org.photonvision.targeting.*;

// Needed for optional shims
import java.util.function.BiConsumer;
import java.util.function.Function;

// WPILib imports (if any)
import org.wpilib.util.struct.Struct;


/**
 * Auto-generated serialization/deserialization helper for Float64TestMessage
 */
public class Float64TestMessageSerde implements PacketSerde<Float64TestMessage> {

    @Override
    public final String getInterfaceUUID() { return "bc96c1f7d9db9371269d0e4f4d4b4cb2"; }
    @Override
    public final String getSchema() { return "float64 test;float64 vlaTest[?];optional float64 optTest;"; }
    @Override
    public final String getTypeName() { return "Float64TestMessage"; }

    @Override
    public int getMaxByteSize() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'getMaxByteSize'");
    }
    @Override
    public void pack(Packet packet, Float64TestMessage value) {
        // field test is of intrinsic type float64
        packet.encode(value.test);

        // vlaTest is an intrinsic VLA!
        packet.encodeListImpl(value.vlaTest,PacketUtils::packDouble);

        // optTest is optional! it better not be a VLA too
        packet.encodeOptionalImpl(value.optTest,PacketUtils::packDouble);
    }

    @Override
    public Float64TestMessage unpack(Packet packet) {
        var ret = new Float64TestMessage();

        // test is of intrinsic type float64
        ret.test = packet.decodeDouble();

        // vlaTest is an intrinsic VLA!
        ret.vlaTest = packet.decodeListImpl(PacketUtils::unpackDouble);

        // optTest is optional! it better not be a VLA too
        ret.optTest = packet.decodeOptionalImpl(PacketUtils::unpackDouble);

        return ret;
    }

    @Override
    public PacketSerde<?>[] getNestedPhotonMessages() {
        return new PacketSerde<?>[] {
            
        };
    }

    @Override
    public Struct<?>[] getNestedWpilibMessages() {
        return new Struct<?>[] {
            
        };
    }
}
