/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_NerualNetwork */

#ifndef _Included_jni_NerualNetwork
#define _Included_jni_NerualNetwork
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_NerualNetwork
 * Method:    initModel
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jni_NerualNetwork_initModel
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jni_NerualNetwork
 * Method:    runModel
 * Signature: (JJ)[F
 */
JNIEXPORT jfloatArray JNICALL Java_jni_NerualNetwork_runModel
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jni_NerualNetwork
 * Method:    releaseModel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jni_NerualNetwork_releaseModel
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
