/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_NerualNetwork_NerualNetwork */

#ifndef _Included_jni_NerualNetwork_NerualNetwork
#define _Included_jni_NerualNetwork_NerualNetwork
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_NerualNetwork_NerualNetwork
 * Method:    initModel
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jni_NerualNetwork_NerualNetwork_initModel
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jni_NerualNetwork_NerualNetwork
 * Method:    runInference
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_jni_NerualNetwork_NerualNetwork_runInference
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jni_NerualNetwork_NerualNetwork
 * Method:    destroyModel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jni_NerualNetwork_NerualNetwork_destroyModel
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
