#
# MIT License
#
# Copyright (c) PhotonVision
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

###############################################################################
## THIS FILE WAS AUTO-GENERATED BY ./photon-serde/generate_messages.py.
##                        --> DO NOT MODIFY <--
###############################################################################

from typing import TYPE_CHECKING


from photonlibpy.packet import Packet
from photonlibpy.targeting import *  # noqa
from . import *



if TYPE_CHECKING:
    from .Float32TestMessage import Float32TestMessage  # noqa


class Float32TestMessageSerde:
    # Message definition md5sum. See photon_packet.adoc for details
    MESSAGE_VERSION = "9fd9ed51ec69d6738ee24af43b2b9c7e"
    MESSAGE_FORMAT = "float32 test;float32 vlaTest[?];optional float32 optTest;"

    @staticmethod
    def pack(value: "Float32TestMessage") -> "Packet":
        ret = Packet()

        # test is of intrinsic type float32
        ret.encodeFloat(value.test)

        # vlaTest is a custom VLA!
        ret.encodeListShimmed(value.vlaTest, ret.encodeFloat)

        # optTest is optional! it better not be a VLA too
        ret.encodeOptionalShimmed(value.optTest, ret.encodeFloat)
        return ret

    @staticmethod
    def unpack(packet: "Packet") -> "Float32TestMessage":
        ret = Float32TestMessage()

        # test is of intrinsic type float32
        ret.test = packet.decodeFloat()

        # vlaTest is an intrinsic VLA!
        ret.vlaTest = packet.decodeListShimmed(packet.decodeFloat)

        # optTest is optional! it better not be a VLA too
        ret.optTest = packet.decodeOptionalShimmed(packet.decodeFloat)

        return ret


# Hack ourselves into the base class
Float32TestMessage.photonStruct = Float32TestMessageSerde()
