#
# MIT License
#
# Copyright (c) PhotonVision
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

###############################################################################
## THIS FILE WAS AUTO-GENERATED BY ./photon-serde/generate_messages.py.
##                        --> DO NOT MODIFY <--
###############################################################################

from typing import TYPE_CHECKING


from photonlibpy.packet import Packet
from photonlibpy.targeting import *  # noqa
from . import *



if TYPE_CHECKING:
    from .Int16TestMessage import Int16TestMessage  # noqa


class Int16TestMessageSerde:
    # Message definition md5sum. See photon_packet.adoc for details
    MESSAGE_VERSION = "23e6ccab160b942600aae8e94a72778a"
    MESSAGE_FORMAT = "int16 test;int16 vlaTest[?];optional int16 optTest;"

    @staticmethod
    def pack(value: "Int16TestMessage") -> "Packet":
        ret = Packet()

        # test is of intrinsic type int16
        ret.encode16(value.test)

        # vlaTest is a custom VLA!
        ret.encodeListShimmed(value.vlaTest, ret.encode16)

        # optTest is optional! it better not be a VLA too
        ret.encodeOptionalShimmed(value.optTest, ret.encode16)
        return ret

    @staticmethod
    def unpack(packet: "Packet") -> "Int16TestMessage":
        ret = Int16TestMessage()

        # test is of intrinsic type int16
        ret.test = packet.decode16()

        # vlaTest is an intrinsic VLA!
        ret.vlaTest = packet.decodeListShimmed(packet.decode16)

        # optTest is optional! it better not be a VLA too
        ret.optTest = packet.decodeOptionalShimmed(packet.decode16)

        return ret


# Hack ourselves into the base class
Int16TestMessage.photonStruct = Int16TestMessageSerde()
