#
# MIT License
#
# Copyright (c) PhotonVision
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

###############################################################################
## THIS FILE WAS AUTO-GENERATED BY ./photon-serde/generate_messages.py.
##                        --> DO NOT MODIFY <--
###############################################################################

from typing import TYPE_CHECKING


from photonlib.packet import Packet
from photonlib.targeting import *  # noqa



if TYPE_CHECKING:
    from .Int32TestMessage import Int32TestMessage  # noqa


class Int32TestMessageSerde:
    # Message definition md5sum. See photon_packet.adoc for details
    MESSAGE_VERSION = "d8596149c4701e7b8912df238cd4ec66"
    MESSAGE_FORMAT = "int32 test;int32 vlaTest[?];optional int32 optTest;"

    @staticmethod
    def pack(value: "Int32TestMessage") -> "Packet":
        ret = Packet()

        # test is of intrinsic type int32
        ret.encodeInt(value.test)

        # vlaTest is a custom VLA!
        ret.encodeListShimmed(value.vlaTest, ret.encodeInt)

        # optTest is optional! it better not be a VLA too
        ret.encodeOptionalShimmed(value.optTest, ret.encodeInt)
        return ret

    @staticmethod
    def unpack(packet: "Packet") -> "Int32TestMessage":
        ret = Int32TestMessage()

        # test is of intrinsic type int32
        ret.test = packet.decodeInt()

        # vlaTest is an intrinsic VLA!
        ret.vlaTest = packet.decodeListShimmed(packet.decodeInt)

        # optTest is optional! it better not be a VLA too
        ret.optTest = packet.decodeOptionalShimmed(packet.decodeInt)

        return ret


# Hack ourselves into the base class
Int32TestMessage.photonStruct = Int32TestMessageSerde()
