#
# MIT License
#
# Copyright (c) PhotonVision
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

###############################################################################
## THIS FILE WAS AUTO-GENERATED BY ./photon-serde/generate_messages.py.
##                        --> DO NOT MODIFY <--
###############################################################################

from typing import TYPE_CHECKING


from photonlibpy.packet import Packet
from photonlibpy.targeting import *  # noqa



if TYPE_CHECKING:
    from .Int64TestMessage import Int64TestMessage  # noqa


class Int64TestMessageSerde:
    # Message definition md5sum. See photon_packet.adoc for details
    MESSAGE_VERSION = "dd2e470b4d07bbcd208906c26a2ae37a"
    MESSAGE_FORMAT = "int64 test;int64 vlaTest[?];optional int64 optTest;"

    @staticmethod
    def pack(value: "Int64TestMessage") -> "Packet":
        ret = Packet()

        # test is of intrinsic type int64
        ret.encodeLong(value.test)

        # vlaTest is a custom VLA!
        ret.encodeListShimmed(value.vlaTest, ret.encodeLong)

        # optTest is optional! it better not be a VLA too
        ret.encodeOptionalShimmed(value.optTest, ret.encodeLong)
        return ret

    @staticmethod
    def unpack(packet: "Packet") -> "Int64TestMessage":
        ret = Int64TestMessage()

        # test is of intrinsic type int64
        ret.test = packet.decodeLong()

        # vlaTest is an intrinsic VLA!
        ret.vlaTest = packet.decodeListShimmed(packet.decodeLong)

        # optTest is optional! it better not be a VLA too
        ret.optTest = packet.decodeOptionalShimmed(packet.decodeLong)

        return ret


# Hack ourselves into the base class
Int64TestMessage.photonStruct = Int64TestMessageSerde()
