#
# MIT License
#
# Copyright (c) PhotonVision
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

###############################################################################
## THIS FILE WAS AUTO-GENERATED BY ./photon-serde/generate_messages.py.
##                        --> DO NOT MODIFY <--
###############################################################################

from typing import TYPE_CHECKING


from photonlibpy.packet import Packet
from photonlibpy.targeting import *  # noqa



if TYPE_CHECKING:
    from .Int8TestMessage import Int8TestMessage  # noqa


class Int8TestMessageSerde:
    # Message definition md5sum. See photon_packet.adoc for details
    MESSAGE_VERSION = "76297a79f30e4d995b8f95c5fa6297fa"
    MESSAGE_FORMAT = "int8 test;int8 vlaTest[?];optional int8 optTest;"

    @staticmethod
    def pack(value: "Int8TestMessage") -> "Packet":
        ret = Packet()

        # test is of intrinsic type int8
        ret.encode8(value.test)

        # vlaTest is a custom VLA!
        ret.encodeListShimmed(value.vlaTest, ret.encode8)

        # optTest is optional! it better not be a VLA too
        ret.encodeOptionalShimmed(value.optTest, ret.encode8)
        return ret

    @staticmethod
    def unpack(packet: "Packet") -> "Int8TestMessage":
        ret = Int8TestMessage()

        # test is of intrinsic type int8
        ret.test = packet.decode8()

        # vlaTest is an intrinsic VLA!
        ret.vlaTest = packet.decodeListShimmed(packet.decode8)

        # optTest is optional! it better not be a VLA too
        ret.optTest = packet.decodeOptionalShimmed(packet.decode8)

        return ret


# Hack ourselves into the base class
Int8TestMessage.photonStruct = Int8TestMessageSerde()
