#
# MIT License
#
# Copyright (c) PhotonVision
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

###############################################################################
## THIS FILE WAS AUTO-GENERATED BY ./photon-serde/generate_messages.py.
##                        --> DO NOT MODIFY <--
###############################################################################

from typing import TYPE_CHECKING, Optional, ClassVar
from dataclasses import dataclass

from photonlib.packet import Packet
from photonlib.targeting import *  # noqa

from .Transform3dTestMessageSerde import Transform3dTestMessageSerde  # noqa

from wpimath.geometry import Transform3d


class _Transform3dTestMessage_test_PLACEHOLDER:
    __slots__ = ()
    def __repr__(self):
        return f"<Placeholder for field 'test'>"

    def __eq__(self, other):
        return isinstance(other, _Transform3dTestMessage_test_PLACEHOLDER)

class _Transform3dTestMessage_vlaTest_PLACEHOLDER:
    __slots__ = ()
    def __repr__(self):
        return f"<Placeholder for field 'vlaTest'>"

    def __eq__(self, other):
        return isinstance(other, _Transform3dTestMessage_vlaTest_PLACEHOLDER)

class _Transform3dTestMessage_optTest_PLACEHOLDER:
    __slots__ = ()
    def __repr__(self):
        return f"<Placeholder for field 'optTest'>"

    def __eq__(self, other):
        return isinstance(other, _Transform3dTestMessage_optTest_PLACEHOLDER)

Transform3dTestMessage_test_PLACEHOLDER = _Transform3dTestMessage_test_PLACEHOLDER()
Transform3dTestMessage_vlaTest_PLACEHOLDER = _Transform3dTestMessage_vlaTest_PLACEHOLDER()
Transform3dTestMessage_optTest_PLACEHOLDER = _Transform3dTestMessage_optTest_PLACEHOLDER()


@dataclass(kw_only=True)
class Transform3dTestMessage:
    test: Transform3d | _Transform3dTestMessage_test_PLACEHOLDER = Transform3dTestMessage_test_PLACEHOLDER
    vlaTest: list[Transform3d] | _Transform3dTestMessage_vlaTest_PLACEHOLDER = Transform3dTestMessage_vlaTest_PLACEHOLDER
    optTest: Optional[Transform3d] | _Transform3dTestMessage_optTest_PLACEHOLDER = Transform3dTestMessage_optTest_PLACEHOLDER
    photonStruct: ClassVar[Transform3dTestMessageSerde]