

class MultiTargetPNPResult:
    @property
    def fiducialIDsUsed(self) -> list[int]: ...

class PhotonCamera:
    def __init__(self, arg: str, /) -> None: ...

    def GetDriverMode(self) -> bool: ...

    def GetLatestResult(self) -> PhotonPipelineResult: ...

class PhotonPipelineMetadata:
    @property
    def sequenceID(self) -> int: ...

    @property
    def captureTimestampMicros(self) -> int: ...

    @property
    def publishTimestampMicros(self) -> int: ...

class PhotonPipelineResult:
    @property
    def metadata(self) -> PhotonPipelineMetadata: ...

    @property
    def targets(self) -> list[PhotonTrackedTarget]: ...

    @property
    def multitagResult(self) -> MultiTargetPNPResult | None: ...

class PhotonTrackedTarget:
    @property
    def yaw(self) -> float: ...

    @property
    def pitch(self) -> float: ...

    def __repr__(self) -> str: ...
