apply plugin: "application"
apply plugin: 'com.gradleup.shadow'

apply from: "${rootDir}/shared/common.gradle"

dependencies {
    implementation project(':photon-core')
}

group = 'org.photonvision'
version  = versionString

application {
    mainClass = 'org.photonvision.CalibrationTool'
}

jar {
    from file("$rootDir/LICENSE")
}

shadowJar {
    archiveBaseName = "photon-calibration-tool"
    archiveVersion = project.version as String
    archiveClassifier.set(wpilibTools.currentPlatform.platformName)
    configurations = [
        project.configurations.runtimeClasspath
    ]
    mergeServiceFiles()
    // SQLite natives that we don't use
    exclude 'org/sqlite/native/*/x86/**'
    exclude 'org/sqlite/native/*/armv7/**'
    exclude 'org/sqlite/native/Linux/arm/**'
    exclude 'org/sqlite/native/Linux/armv6/**'
    exclude 'org/sqlite/native/Linux/ppc64/**'
    exclude 'org/sqlite/native/Linux-Android/**'
    exclude 'org/sqlite/native/Linux-Musl/**'
    exclude 'org/sqlite/native/FreeBSD/**'
    // JNA natives that we don't use
    exclude 'com/sun/jna/*bsd*/**'
    exclude 'com/sun/jna/*ppc*/**'
    exclude 'com/sun/jna/*-x86/**'
    exclude 'com/sun/jna/linux-arm*/**' // Non-aarch64 platforms only
    exclude 'com/sun/jna/linux-loongarch64/**'
    exclude 'com/sun/jna/linux-mips64el/**'
    exclude 'com/sun/jna/linux-riscv64/**'
    exclude 'com/sun/jna/linux-s390x/**'
    exclude 'com/sun/jna/sunos*/**'
}

run {
    environment "PATH_PREFIX", "../"

    if (project.hasProperty("profile")) {
        jvmArgs=[
            "-Dcom.sun.management.jmxremote=true",
            "-Dcom.sun.management.jmxremote.ssl=false",
            "-Dcom.sun.management.jmxremote.authenticate=false",
            "-Dcom.sun.management.jmxremote.port=5000",
            "-Djava.rmi.server.hostname=0.0.0.0",
        ]
    }
}
