/*
 * MIT License
 *
 * Copyright (c) PhotonVision
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#pragma once

// THIS FILE WAS AUTO-GENERATED BY ./photon-serde/generate_messages.py. DO NOT MODIFY

#include "photon/struct/Transform3dTestMessageStruct.h"

namespace photon {
/**
 * Auto-generated ser/de test class, not intended for use in actual dataflow
 */
class Transform3dTestMessage : public Transform3dTestMessage_PhotonStruct {
    using Base = Transform3dTestMessage_PhotonStruct;

public:
    Transform3dTestMessage() = default;

    explicit Transform3dTestMessage(Base&& data) : Base(data) {}

    template <typename... Args>
    explicit Transform3dTestMessage(Args&&... args)
        : Base{std::forward<Args>(args)...} {}

    friend bool operator==(Transform3dTestMessage const&, Transform3dTestMessage const&) = default;
};
} // namespace photon

#include "photon/serde/Transform3dTestMessageSerde.h"