/*
 * MIT License
 *
 * Copyright (c) PhotonVision
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// THIS FILE WAS AUTO-GENERATED BY ./photon-serde/generate_messages.py. DO NOT MODIFY

package org.photonvision.targeting;

import java.util.List;
import java.util.Optional;

import org.photonvision.struct.Int32TestMessageSerde;
import org.photonvision.common.dataflow.structures.PacketSerde;
import org.photonvision.targeting.serde.PhotonStructSerializable;

// WPILib imports (if any)
import org.wpilib.util.struct.Struct;


/**
 * Auto-generated ser/de test class, not intended for use in actual dataflow
 */
public class Int32TestMessage implements PhotonStructSerializable<Int32TestMessage> {

    public int test;
    public List<Integer> vlaTest = List.of();
    public Optional<Integer> optTest = Optional.empty();

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;

        Int32TestMessage other = (Int32TestMessage) obj;
        if (this.test != other.test) return false;
        if (!this.vlaTest.equals(other.vlaTest)) return false;
        if (!this.optTest.equals(other.optTest)) return false;
        return true;
    }

    /** Int32TestMessage PhotonStruct for serialization. */
    public static final Int32TestMessageSerde photonStruct = new Int32TestMessageSerde();

    @Override
    public PacketSerde<Int32TestMessage> getSerde() {
        return photonStruct;
    }

    @Override
    public String toString() {
        return "Int32TestMessage ["
        + "test="
        + test
        + ", vlaTest="
        + vlaTest
        + ", optTest="
        + optTest
        + "]";
    }
}