/*
 * MIT License
 *
 * Copyright (c) PhotonVision
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// THIS FILE WAS AUTO-GENERATED BY ./photon-serde/generate_messages.py. DO NOT MODIFY

package org.photonvision.targeting;

import java.util.List;
import java.util.Optional;

import org.photonvision.struct.Transform3dTestMessageSerde;
import org.photonvision.common.dataflow.structures.PacketSerde;
import org.photonvision.targeting.serde.PhotonStructSerializable;

// WPILib imports (if any)
import org.wpilib.util.struct.Struct;
import org.wpilib.math.geometry.Transform3d;

/**
 * Auto-generated ser/de test class, not intended for use in actual dataflow
 */
public class Transform3dTestMessage implements PhotonStructSerializable<Transform3dTestMessage> {

    public Transform3d test = new Transform3d();
    public List<Transform3d> vlaTest = List.of();
    public Optional<Transform3d> optTest = Optional.empty();

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;

        Transform3dTestMessage other = (Transform3dTestMessage) obj;
        if (!this.test.equals(other.test)) return false;
        if (!this.vlaTest.equals(other.vlaTest)) return false;
        if (!this.optTest.equals(other.optTest)) return false;
        return true;
    }

    /** Transform3dTestMessage PhotonStruct for serialization. */
    public static final Transform3dTestMessageSerde photonStruct = new Transform3dTestMessageSerde();

    @Override
    public PacketSerde<Transform3dTestMessage> getSerde() {
        return photonStruct;
    }

    @Override
    public String toString() {
        return "Transform3dTestMessage ["
        + "test="
        + test.toString()
        + ", vlaTest="
        + vlaTest.toString()
        + ", optTest="
        + optTest.toString()
        + "]";
    }
}