/*
 * MIT License
 *
 * Copyright (c) PhotonVision
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#pragma once

// THIS FILE WAS AUTO-GENERATED BY ./photon-serde/generate_messages.py. DO NOT MODIFY

#include <wpi/util/SymbolExports.hpp>

// Include myself
#include "photon/dataflow/structures/Packet.h"
#include "photon/targeting/Int32TestMessage.h"

// Includes for dependant types
#include <optional>
#include <stdint.h>
#include <vector>


namespace photon {

template <>
struct WPILIB_DLLEXPORT SerdeType<Int32TestMessage> {
  static constexpr std::string_view GetSchemaHash() {
    return "d8596149c4701e7b8912df238cd4ec66";
  }

  static constexpr std::string_view GetSchema() {
    return "int32 test;int32 vlaTest[?];optional int32 optTest;";
  }

  static photon::Int32TestMessage Unpack(photon::Packet& packet);
  static void Pack(photon::Packet& packet, const photon::Int32TestMessage& value);
};

static_assert(photon::PhotonStructSerializable<photon::Int32TestMessage>);

} // namespace photon
