// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               v3.21.12
// source: wpimath/protobuf/geometry3d.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "wpi.proto";

export interface ProtobufTranslation3d {
  x: number;
  y: number;
  z: number;
}

export interface ProtobufQuaternion {
  w: number;
  x: number;
  y: number;
  z: number;
}

export interface ProtobufRotation3d {
  q: ProtobufQuaternion | undefined;
}

export interface ProtobufPose3d {
  translation: ProtobufTranslation3d | undefined;
  rotation: ProtobufRotation3d | undefined;
}

export interface ProtobufTransform3d {
  translation: ProtobufTranslation3d | undefined;
  rotation: ProtobufRotation3d | undefined;
}

export interface ProtobufTwist3d {
  dx: number;
  dy: number;
  dz: number;
  rx: number;
  ry: number;
  rz: number;
}

function createBaseProtobufTranslation3d(): ProtobufTranslation3d {
  return { x: 0, y: 0, z: 0 };
}

export const ProtobufTranslation3d: MessageFns<ProtobufTranslation3d> = {
  encode(message: ProtobufTranslation3d, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.x !== 0) {
      writer.uint32(9).double(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(17).double(message.y);
    }
    if (message.z !== 0) {
      writer.uint32(25).double(message.z);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProtobufTranslation3d {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseProtobufTranslation3d();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 9) {
              break;
            }

            message.x = reader.double();
            continue;
          }
          case 2: {
            if (tag !== 17) {
              break;
            }

            message.y = reader.double();
            continue;
          }
          case 3: {
            if (tag !== 25) {
              break;
            }

            message.z = reader.double();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ProtobufTranslation3d {
    return {
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
      z: isSet(object.z) ? globalThis.Number(object.z) : 0,
    };
  },

  toJSON(message: ProtobufTranslation3d): unknown {
    const obj: any = {};
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    if (message.z !== 0) {
      obj.z = message.z;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProtobufTranslation3d>, I>>(base?: I): ProtobufTranslation3d {
    return ProtobufTranslation3d.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProtobufTranslation3d>, I>>(object: I): ProtobufTranslation3d {
    const message = createBaseProtobufTranslation3d();
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    message.z = object.z ?? 0;
    return message;
  },
};

function createBaseProtobufQuaternion(): ProtobufQuaternion {
  return { w: 0, x: 0, y: 0, z: 0 };
}

export const ProtobufQuaternion: MessageFns<ProtobufQuaternion> = {
  encode(message: ProtobufQuaternion, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.w !== 0) {
      writer.uint32(9).double(message.w);
    }
    if (message.x !== 0) {
      writer.uint32(17).double(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(25).double(message.y);
    }
    if (message.z !== 0) {
      writer.uint32(33).double(message.z);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProtobufQuaternion {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseProtobufQuaternion();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 9) {
              break;
            }

            message.w = reader.double();
            continue;
          }
          case 2: {
            if (tag !== 17) {
              break;
            }

            message.x = reader.double();
            continue;
          }
          case 3: {
            if (tag !== 25) {
              break;
            }

            message.y = reader.double();
            continue;
          }
          case 4: {
            if (tag !== 33) {
              break;
            }

            message.z = reader.double();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ProtobufQuaternion {
    return {
      w: isSet(object.w) ? globalThis.Number(object.w) : 0,
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
      z: isSet(object.z) ? globalThis.Number(object.z) : 0,
    };
  },

  toJSON(message: ProtobufQuaternion): unknown {
    const obj: any = {};
    if (message.w !== 0) {
      obj.w = message.w;
    }
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    if (message.z !== 0) {
      obj.z = message.z;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProtobufQuaternion>, I>>(base?: I): ProtobufQuaternion {
    return ProtobufQuaternion.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProtobufQuaternion>, I>>(object: I): ProtobufQuaternion {
    const message = createBaseProtobufQuaternion();
    message.w = object.w ?? 0;
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    message.z = object.z ?? 0;
    return message;
  },
};

function createBaseProtobufRotation3d(): ProtobufRotation3d {
  return { q: undefined };
}

export const ProtobufRotation3d: MessageFns<ProtobufRotation3d> = {
  encode(message: ProtobufRotation3d, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.q !== undefined) {
      ProtobufQuaternion.encode(message.q, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProtobufRotation3d {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseProtobufRotation3d();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.q = ProtobufQuaternion.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ProtobufRotation3d {
    return { q: isSet(object.q) ? ProtobufQuaternion.fromJSON(object.q) : undefined };
  },

  toJSON(message: ProtobufRotation3d): unknown {
    const obj: any = {};
    if (message.q !== undefined) {
      obj.q = ProtobufQuaternion.toJSON(message.q);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProtobufRotation3d>, I>>(base?: I): ProtobufRotation3d {
    return ProtobufRotation3d.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProtobufRotation3d>, I>>(object: I): ProtobufRotation3d {
    const message = createBaseProtobufRotation3d();
    message.q = (object.q !== undefined && object.q !== null) ? ProtobufQuaternion.fromPartial(object.q) : undefined;
    return message;
  },
};

function createBaseProtobufPose3d(): ProtobufPose3d {
  return { translation: undefined, rotation: undefined };
}

export const ProtobufPose3d: MessageFns<ProtobufPose3d> = {
  encode(message: ProtobufPose3d, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.translation !== undefined) {
      ProtobufTranslation3d.encode(message.translation, writer.uint32(10).fork()).join();
    }
    if (message.rotation !== undefined) {
      ProtobufRotation3d.encode(message.rotation, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProtobufPose3d {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseProtobufPose3d();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.translation = ProtobufTranslation3d.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.rotation = ProtobufRotation3d.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ProtobufPose3d {
    return {
      translation: isSet(object.translation) ? ProtobufTranslation3d.fromJSON(object.translation) : undefined,
      rotation: isSet(object.rotation) ? ProtobufRotation3d.fromJSON(object.rotation) : undefined,
    };
  },

  toJSON(message: ProtobufPose3d): unknown {
    const obj: any = {};
    if (message.translation !== undefined) {
      obj.translation = ProtobufTranslation3d.toJSON(message.translation);
    }
    if (message.rotation !== undefined) {
      obj.rotation = ProtobufRotation3d.toJSON(message.rotation);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProtobufPose3d>, I>>(base?: I): ProtobufPose3d {
    return ProtobufPose3d.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProtobufPose3d>, I>>(object: I): ProtobufPose3d {
    const message = createBaseProtobufPose3d();
    message.translation = (object.translation !== undefined && object.translation !== null)
      ? ProtobufTranslation3d.fromPartial(object.translation)
      : undefined;
    message.rotation = (object.rotation !== undefined && object.rotation !== null)
      ? ProtobufRotation3d.fromPartial(object.rotation)
      : undefined;
    return message;
  },
};

function createBaseProtobufTransform3d(): ProtobufTransform3d {
  return { translation: undefined, rotation: undefined };
}

export const ProtobufTransform3d: MessageFns<ProtobufTransform3d> = {
  encode(message: ProtobufTransform3d, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.translation !== undefined) {
      ProtobufTranslation3d.encode(message.translation, writer.uint32(10).fork()).join();
    }
    if (message.rotation !== undefined) {
      ProtobufRotation3d.encode(message.rotation, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProtobufTransform3d {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseProtobufTransform3d();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.translation = ProtobufTranslation3d.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.rotation = ProtobufRotation3d.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ProtobufTransform3d {
    return {
      translation: isSet(object.translation) ? ProtobufTranslation3d.fromJSON(object.translation) : undefined,
      rotation: isSet(object.rotation) ? ProtobufRotation3d.fromJSON(object.rotation) : undefined,
    };
  },

  toJSON(message: ProtobufTransform3d): unknown {
    const obj: any = {};
    if (message.translation !== undefined) {
      obj.translation = ProtobufTranslation3d.toJSON(message.translation);
    }
    if (message.rotation !== undefined) {
      obj.rotation = ProtobufRotation3d.toJSON(message.rotation);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProtobufTransform3d>, I>>(base?: I): ProtobufTransform3d {
    return ProtobufTransform3d.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProtobufTransform3d>, I>>(object: I): ProtobufTransform3d {
    const message = createBaseProtobufTransform3d();
    message.translation = (object.translation !== undefined && object.translation !== null)
      ? ProtobufTranslation3d.fromPartial(object.translation)
      : undefined;
    message.rotation = (object.rotation !== undefined && object.rotation !== null)
      ? ProtobufRotation3d.fromPartial(object.rotation)
      : undefined;
    return message;
  },
};

function createBaseProtobufTwist3d(): ProtobufTwist3d {
  return { dx: 0, dy: 0, dz: 0, rx: 0, ry: 0, rz: 0 };
}

export const ProtobufTwist3d: MessageFns<ProtobufTwist3d> = {
  encode(message: ProtobufTwist3d, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.dx !== 0) {
      writer.uint32(9).double(message.dx);
    }
    if (message.dy !== 0) {
      writer.uint32(17).double(message.dy);
    }
    if (message.dz !== 0) {
      writer.uint32(25).double(message.dz);
    }
    if (message.rx !== 0) {
      writer.uint32(33).double(message.rx);
    }
    if (message.ry !== 0) {
      writer.uint32(41).double(message.ry);
    }
    if (message.rz !== 0) {
      writer.uint32(49).double(message.rz);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProtobufTwist3d {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseProtobufTwist3d();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 9) {
              break;
            }

            message.dx = reader.double();
            continue;
          }
          case 2: {
            if (tag !== 17) {
              break;
            }

            message.dy = reader.double();
            continue;
          }
          case 3: {
            if (tag !== 25) {
              break;
            }

            message.dz = reader.double();
            continue;
          }
          case 4: {
            if (tag !== 33) {
              break;
            }

            message.rx = reader.double();
            continue;
          }
          case 5: {
            if (tag !== 41) {
              break;
            }

            message.ry = reader.double();
            continue;
          }
          case 6: {
            if (tag !== 49) {
              break;
            }

            message.rz = reader.double();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ProtobufTwist3d {
    return {
      dx: isSet(object.dx) ? globalThis.Number(object.dx) : 0,
      dy: isSet(object.dy) ? globalThis.Number(object.dy) : 0,
      dz: isSet(object.dz) ? globalThis.Number(object.dz) : 0,
      rx: isSet(object.rx) ? globalThis.Number(object.rx) : 0,
      ry: isSet(object.ry) ? globalThis.Number(object.ry) : 0,
      rz: isSet(object.rz) ? globalThis.Number(object.rz) : 0,
    };
  },

  toJSON(message: ProtobufTwist3d): unknown {
    const obj: any = {};
    if (message.dx !== 0) {
      obj.dx = message.dx;
    }
    if (message.dy !== 0) {
      obj.dy = message.dy;
    }
    if (message.dz !== 0) {
      obj.dz = message.dz;
    }
    if (message.rx !== 0) {
      obj.rx = message.rx;
    }
    if (message.ry !== 0) {
      obj.ry = message.ry;
    }
    if (message.rz !== 0) {
      obj.rz = message.rz;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProtobufTwist3d>, I>>(base?: I): ProtobufTwist3d {
    return ProtobufTwist3d.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProtobufTwist3d>, I>>(object: I): ProtobufTwist3d {
    const message = createBaseProtobufTwist3d();
    message.dx = object.dx ?? 0;
    message.dy = object.dy ?? 0;
    message.dz = object.dz ?? 0;
    message.rx = object.rx ?? 0;
    message.ry = object.ry ?? 0;
    message.rz = object.rz ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
