
// This header file is automatically generated by semiwrap and provides the
// `initWrapper` function which is used to instantiate all the wrapper code
// autogenerated by semiwrap
//
// The name of the header will be `semiwrap_init.PACKAGE.NAME.hpp`
#include <semiwrap_init.photonlibpy._photonlibpy.hpp>

SEMIWRAP_PYBIND11_MODULE(m) {
    initWrapper(m);
}