#
# MIT License
#
# Copyright (c) PhotonVision
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

###############################################################################
## THIS FILE WAS AUTO-GENERATED BY ./photon-serde/generate_messages.py.
##                        --> DO NOT MODIFY <--
###############################################################################

from photonlibpy.packet import Packet
from photonlibpy.targeting import *
from .messages import *

from wpimath import Rotation3d
from wpimath import Translation3d
from wpimath import Transform3d


def AutoSerdeTest(data) -> bool:
    packet = data.photonStruct.pack(data)
    unpacked = data.photonStruct.unpack(packet)
    print(f"Original: {data}")
    print(f"Unpacked: {unpacked}")
    return data == unpacked


def test_Int8Test():
    print("Running Int8Test...")
    
    print("Test case default_test:")
    default_test = Int8TestMessage()
    assert AutoSerdeTest(default_test)
    
    print("Test case optional_test:")
    optional_test = Int8TestMessage()
    optional_test.optTest = 3
    assert AutoSerdeTest(optional_test)
    
    print("Test case vla_test:")
    vla_test = Int8TestMessage()
    vla_test.vlaTest = [1, 2, 3]
    assert AutoSerdeTest(vla_test)
    
    print("Test case general_test:")
    general_test = Int8TestMessage()
    general_test.test = 42
    general_test.optTest = 7
    general_test.vlaTest = [4, 5, 6]
    assert AutoSerdeTest(general_test)
    

def test_Int16Test():
    print("Running Int16Test...")
    
    print("Test case default_test:")
    default_test = Int16TestMessage()
    assert AutoSerdeTest(default_test)
    
    print("Test case optional_test:")
    optional_test = Int16TestMessage()
    optional_test.optTest = 3
    assert AutoSerdeTest(optional_test)
    
    print("Test case vla_test:")
    vla_test = Int16TestMessage()
    vla_test.vlaTest = [1, 2, 3]
    assert AutoSerdeTest(vla_test)
    
    print("Test case general_test:")
    general_test = Int16TestMessage()
    general_test.test = 42
    general_test.optTest = 7
    general_test.vlaTest = [4, 5, 6]
    assert AutoSerdeTest(general_test)
    

def test_Int32Test():
    print("Running Int32Test...")
    
    print("Test case default_test:")
    default_test = Int32TestMessage()
    assert AutoSerdeTest(default_test)
    
    print("Test case optional_test:")
    optional_test = Int32TestMessage()
    optional_test.optTest = 3
    assert AutoSerdeTest(optional_test)
    
    print("Test case vla_test:")
    vla_test = Int32TestMessage()
    vla_test.vlaTest = [1, 2, 3]
    assert AutoSerdeTest(vla_test)
    
    print("Test case general_test:")
    general_test = Int32TestMessage()
    general_test.test = 42
    general_test.optTest = 7
    general_test.vlaTest = [4, 5, 6]
    assert AutoSerdeTest(general_test)
    

def test_Int64Test():
    print("Running Int64Test...")
    
    print("Test case default_test:")
    default_test = Int64TestMessage()
    assert AutoSerdeTest(default_test)
    
    print("Test case optional_test:")
    optional_test = Int64TestMessage()
    optional_test.optTest = 3
    assert AutoSerdeTest(optional_test)
    
    print("Test case vla_test:")
    vla_test = Int64TestMessage()
    vla_test.vlaTest = [1, 2, 3]
    assert AutoSerdeTest(vla_test)
    
    print("Test case general_test:")
    general_test = Int64TestMessage()
    general_test.test = 42
    general_test.optTest = 7
    general_test.vlaTest = [4, 5, 6]
    assert AutoSerdeTest(general_test)
    

def test_Float32Test():
    print("Running Float32Test...")
    
    print("Test case default_test:")
    default_test = Float32TestMessage()
    assert AutoSerdeTest(default_test)
    
    print("Test case optional_test:")
    optional_test = Float32TestMessage()
    optional_test.optTest = 3.0
    assert AutoSerdeTest(optional_test)
    
    print("Test case vla_test:")
    vla_test = Float32TestMessage()
    vla_test.vlaTest = [1.0, 2.0, 3.0]
    assert AutoSerdeTest(vla_test)
    
    print("Test case general_test:")
    general_test = Float32TestMessage()
    general_test.test = 42.0
    general_test.optTest = 7.0
    general_test.vlaTest = [4.0, 5.0, 6.0]
    assert AutoSerdeTest(general_test)
    

def test_Float64Test():
    print("Running Float64Test...")
    
    print("Test case default_test:")
    default_test = Float64TestMessage()
    assert AutoSerdeTest(default_test)
    
    print("Test case optional_test:")
    optional_test = Float64TestMessage()
    optional_test.optTest = 3.0
    assert AutoSerdeTest(optional_test)
    
    print("Test case vla_test:")
    vla_test = Float64TestMessage()
    vla_test.vlaTest = [1.0, 2.0, 3.0]
    assert AutoSerdeTest(vla_test)
    
    print("Test case general_test:")
    general_test = Float64TestMessage()
    general_test.test = 42.0
    general_test.optTest = 7.0
    general_test.vlaTest = [4.0, 5.0, 6.0]
    assert AutoSerdeTest(general_test)
    

def test_BoolTest():
    print("Running BoolTest...")
    
    print("Test case default_test:")
    default_test = BoolTestMessage()
    assert AutoSerdeTest(default_test)
    
    print("Test case optional_test:")
    optional_test = BoolTestMessage()
    optional_test.optTest = True
    assert AutoSerdeTest(optional_test)
    
    print("Test case vla_test:")
    vla_test = BoolTestMessage()
    vla_test.vlaTest = [True, False, True]
    assert AutoSerdeTest(vla_test)
    
    print("Test case general_test:")
    general_test = BoolTestMessage()
    general_test.test = False
    general_test.optTest = True
    general_test.vlaTest = [True, False, True]
    assert AutoSerdeTest(general_test)
    

def test_Transform3dTest():
    print("Running Transform3dTest...")
    
    print("Test case default_test:")
    default_test = Transform3dTestMessage()
    assert AutoSerdeTest(default_test)
    
    print("Test case optional_test:")
    optional_test = Transform3dTestMessage()
    optional_test.optTest = Transform3d(Translation3d(1.0, 2.0, 3.0), Rotation3d(0.1, 0.2, 0.3))
    assert AutoSerdeTest(optional_test)
    
    print("Test case vla_test:")
    vla_test = Transform3dTestMessage()
    vla_test.vlaTest = [Transform3d(Translation3d(1.0, 2.0, 3.0), Rotation3d(0.1, 0.2, 0.3)), Transform3d(Translation3d(4.0, 5.0, 6.0), Rotation3d(0.4, 0.5, 0.6))]
    assert AutoSerdeTest(vla_test)
    
    print("Test case general_test:")
    general_test = Transform3dTestMessage()
    general_test.test = Transform3d(Translation3d(7.0, 8.0, 9.0), Rotation3d(0.7, 0.8, 0.9))
    general_test.optTest = Transform3d(Translation3d(1.0, 2.0, 3.0), Rotation3d(0.1, 0.2, 0.3))
    general_test.vlaTest = [Transform3d(Translation3d(1.0, 2.0, 3.0), Rotation3d(0.1, 0.2, 0.3)), Transform3d(Translation3d(4.0, 5.0, 6.0), Rotation3d(0.4, 0.5, 0.6))]
    assert AutoSerdeTest(general_test)
    
