import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const dirToAutogenerated = (dirName: string, title: string) => ({
  type: "category",
  label: title,
  link: {
    slug: `/${dirName}`,
    type: "generated-index",
  },
  items: [
    {
      type: "autogenerated",
      dirName,
    },
  ],
});
export default {
  docs: [
    {
      type: "category",
      label: "Getting Started",
      collapsible: false,
      collapsed: false,
      items: [
        "description",
        dirToAutogenerated("hardware", "Hardware Selection"),
        dirToAutogenerated("installation", "Installation & Setup"),
        "settings",
      ],
    },
    {
      type: "category",
      label: "Pipeline Tuning and Calibration",
      collapsible: true,
      collapsed: false,
      items: [
        dirToAutogenerated("pipelines", "Pipelines"),
        dirToAutogenerated("apriltag-pipelines", "AprilTag Detection"),
        dirToAutogenerated("reflectiveAndShape", "Colored Shape & Reflective"),
        dirToAutogenerated("objectDetection", "Object Detection"),
        "calibration/calibration",
      ],
    },
    {
      type: "category",
      label: "Programming Reference",
      collapsible: false,
      collapsed: false,
      items: [
        //"programming/photonlib/index",
        dirToAutogenerated(
          "programming/photonlib",
          "PhotonLib: Robot Code Interface"
        ),
        dirToAutogenerated("simulation", "Simulation"),
        dirToAutogenerated("integration", "Robot Integration"),
        dirToAutogenerated("examples", "Code Examples")
      ],
    },
    {
      type: "category",
      label: "Additional Resources",
      collapsible: false,
      collapsed: false,
      items: [
        dirToAutogenerated("troubleshooting", "Troubleshooting"),
        "additional-resources/best-practices",
        "additional-resources/config",
        "additional-resources/nt-api",
        dirToAutogenerated("contributing", "Contributing to PhotonVision Projects")
      ],
    },
    {
      type: "category",
      label: "API Documentation",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "link",
          label: "Java",
          href: "https://javadocs.photonvision.org",
        },
        {
          type: "link",
          label: "C++",
          href: "https://cppdocs.photonvision.org",
        },
      ],
    },
  ],
};
