// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               v3.21.12
// source: PhotonMessage.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ProtobufTransform3d } from "./wpimath/protobuf/geometry3d";

export const protobufPackage = "photonvision.core.proto";

/** UI -> Frontend format */
export interface VisionModuleEvent {
  cameraUniqueName: string;
  driverMode?: boolean | undefined;
}

export interface CameraCalibrationCoefficients {
  /** TODO fill this out */
  cameraIntrinsics: number[];
}

export interface CalibrationUploadedEvent {
  cameraUniqueName: string;
  newCal: CameraCalibrationCoefficients | undefined;
}

export interface UiChangeEvent {
  /** Messages from UI -> backend */
  vmChange?:
    | VisionModuleEvent
    | undefined;
  /** Messages internal to backend */
  userConnected?: boolean | undefined;
  calibrationUploaded?: CalibrationUploadedEvent | undefined;
}

export interface PhotonTarget {
  yaw: number;
  pitch: number;
  skew: number;
  area: number;
  /** -1 if not set */
  ambiguity: number;
  /** -1 if not set */
  fiducialId: number;
  confidence: number;
  classId: number;
  pose?: ProtobufTransform3d | undefined;
}

export interface MultitagResult {
  bestTransform: ProtobufTransform3d | undefined;
  bestReprojectionError: number;
  fiducialIDsUsed: number[];
}

export interface PipelineResult {
  cameraUniqueName: string;
  sequenceID: number;
  fps: number;
  latency: number;
  focus?: number | undefined;
  targets: PhotonTarget[];
  multitagResult?: MultitagResult | undefined;
  classNames: string[];
}

export interface UiMetrics {
}

export interface LogMessage {
}

export interface UiCalibrationData {
}

export interface VisionSourceManagerState {
}

export interface MutatePipelineSettings {
}

export interface PhotonSettings {
}

export interface CameraSettings {
  nickname: string;
  uniqueName: string;
  inputStreamPort: number;
  outputStreamPort: number;
  isEnabled: boolean;
  isConnected: boolean;
  hasConnected: boolean;
  mismatch: boolean;
}

/** Things backend wants to send to dashboards */
export interface OutgoingDashboardEvent {
  /** Send settings + cameraSettings for "full settings" */
  settings?: PhotonSettings | undefined;
  cameraSettings: CameraSettings[];
  /** Update events */
  updatePipelineResult?: PipelineResult | undefined;
  metrics?: UiMetrics | undefined;
  log?: LogMessage | undefined;
  calibrationData?: UiCalibrationData | undefined;
  visionSourceManager?: VisionSourceManagerState | undefined;
  mutatePipeline?: MutatePipelineSettings | undefined;
}

/** Wrapper created by backend to add context */
export interface PhotonDataChangeEvent {
  /** Websocket session this request came from, if it came from a websocket */
  originCtxSessionId?: string | undefined;
  event: UiChangeEvent | undefined;
}

function createBaseVisionModuleEvent(): VisionModuleEvent {
  return { cameraUniqueName: "", driverMode: undefined };
}

export const VisionModuleEvent: MessageFns<VisionModuleEvent> = {
  encode(message: VisionModuleEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cameraUniqueName !== "") {
      writer.uint32(10).string(message.cameraUniqueName);
    }
    if (message.driverMode !== undefined) {
      writer.uint32(16).bool(message.driverMode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VisionModuleEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseVisionModuleEvent();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.cameraUniqueName = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.driverMode = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): VisionModuleEvent {
    return {
      cameraUniqueName: isSet(object.cameraUniqueName) ? globalThis.String(object.cameraUniqueName) : "",
      driverMode: isSet(object.driverMode) ? globalThis.Boolean(object.driverMode) : undefined,
    };
  },

  toJSON(message: VisionModuleEvent): unknown {
    const obj: any = {};
    if (message.cameraUniqueName !== "") {
      obj.cameraUniqueName = message.cameraUniqueName;
    }
    if (message.driverMode !== undefined) {
      obj.driverMode = message.driverMode;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VisionModuleEvent>, I>>(base?: I): VisionModuleEvent {
    return VisionModuleEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VisionModuleEvent>, I>>(object: I): VisionModuleEvent {
    const message = createBaseVisionModuleEvent();
    message.cameraUniqueName = object.cameraUniqueName ?? "";
    message.driverMode = object.driverMode ?? undefined;
    return message;
  },
};

function createBaseCameraCalibrationCoefficients(): CameraCalibrationCoefficients {
  return { cameraIntrinsics: [] };
}

export const CameraCalibrationCoefficients: MessageFns<CameraCalibrationCoefficients> = {
  encode(message: CameraCalibrationCoefficients, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.cameraIntrinsics) {
      writer.double(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CameraCalibrationCoefficients {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCameraCalibrationCoefficients();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag === 9) {
              message.cameraIntrinsics.push(reader.double());

              continue;
            }

            if (tag === 10) {
              const end2 = reader.uint32() + reader.pos;
              while (reader.pos < end2) {
                message.cameraIntrinsics.push(reader.double());
              }

              continue;
            }

            break;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): CameraCalibrationCoefficients {
    return {
      cameraIntrinsics: globalThis.Array.isArray(object?.cameraIntrinsics)
        ? object.cameraIntrinsics.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: CameraCalibrationCoefficients): unknown {
    const obj: any = {};
    if (message.cameraIntrinsics?.length) {
      obj.cameraIntrinsics = message.cameraIntrinsics;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CameraCalibrationCoefficients>, I>>(base?: I): CameraCalibrationCoefficients {
    return CameraCalibrationCoefficients.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CameraCalibrationCoefficients>, I>>(
    object: I,
  ): CameraCalibrationCoefficients {
    const message = createBaseCameraCalibrationCoefficients();
    message.cameraIntrinsics = object.cameraIntrinsics?.map((e) => e) || [];
    return message;
  },
};

function createBaseCalibrationUploadedEvent(): CalibrationUploadedEvent {
  return { cameraUniqueName: "", newCal: undefined };
}

export const CalibrationUploadedEvent: MessageFns<CalibrationUploadedEvent> = {
  encode(message: CalibrationUploadedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cameraUniqueName !== "") {
      writer.uint32(10).string(message.cameraUniqueName);
    }
    if (message.newCal !== undefined) {
      CameraCalibrationCoefficients.encode(message.newCal, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CalibrationUploadedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCalibrationUploadedEvent();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.cameraUniqueName = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.newCal = CameraCalibrationCoefficients.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): CalibrationUploadedEvent {
    return {
      cameraUniqueName: isSet(object.cameraUniqueName) ? globalThis.String(object.cameraUniqueName) : "",
      newCal: isSet(object.newCal) ? CameraCalibrationCoefficients.fromJSON(object.newCal) : undefined,
    };
  },

  toJSON(message: CalibrationUploadedEvent): unknown {
    const obj: any = {};
    if (message.cameraUniqueName !== "") {
      obj.cameraUniqueName = message.cameraUniqueName;
    }
    if (message.newCal !== undefined) {
      obj.newCal = CameraCalibrationCoefficients.toJSON(message.newCal);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CalibrationUploadedEvent>, I>>(base?: I): CalibrationUploadedEvent {
    return CalibrationUploadedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CalibrationUploadedEvent>, I>>(object: I): CalibrationUploadedEvent {
    const message = createBaseCalibrationUploadedEvent();
    message.cameraUniqueName = object.cameraUniqueName ?? "";
    message.newCal = (object.newCal !== undefined && object.newCal !== null)
      ? CameraCalibrationCoefficients.fromPartial(object.newCal)
      : undefined;
    return message;
  },
};

function createBaseUiChangeEvent(): UiChangeEvent {
  return { vmChange: undefined, userConnected: undefined, calibrationUploaded: undefined };
}

export const UiChangeEvent: MessageFns<UiChangeEvent> = {
  encode(message: UiChangeEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.vmChange !== undefined) {
      VisionModuleEvent.encode(message.vmChange, writer.uint32(10).fork()).join();
    }
    if (message.userConnected !== undefined) {
      writer.uint32(16).bool(message.userConnected);
    }
    if (message.calibrationUploaded !== undefined) {
      CalibrationUploadedEvent.encode(message.calibrationUploaded, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UiChangeEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseUiChangeEvent();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.vmChange = VisionModuleEvent.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.userConnected = reader.bool();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.calibrationUploaded = CalibrationUploadedEvent.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): UiChangeEvent {
    return {
      vmChange: isSet(object.vmChange)
        ? VisionModuleEvent.fromJSON(object.vmChange)
        : isSet(object.vm_change)
        ? VisionModuleEvent.fromJSON(object.vm_change)
        : undefined,
      userConnected: isSet(object.userConnected) ? globalThis.Boolean(object.userConnected) : undefined,
      calibrationUploaded: isSet(object.calibrationUploaded)
        ? CalibrationUploadedEvent.fromJSON(object.calibrationUploaded)
        : undefined,
    };
  },

  toJSON(message: UiChangeEvent): unknown {
    const obj: any = {};
    if (message.vmChange !== undefined) {
      obj.vmChange = VisionModuleEvent.toJSON(message.vmChange);
    }
    if (message.userConnected !== undefined) {
      obj.userConnected = message.userConnected;
    }
    if (message.calibrationUploaded !== undefined) {
      obj.calibrationUploaded = CalibrationUploadedEvent.toJSON(message.calibrationUploaded);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UiChangeEvent>, I>>(base?: I): UiChangeEvent {
    return UiChangeEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UiChangeEvent>, I>>(object: I): UiChangeEvent {
    const message = createBaseUiChangeEvent();
    message.vmChange = (object.vmChange !== undefined && object.vmChange !== null)
      ? VisionModuleEvent.fromPartial(object.vmChange)
      : undefined;
    message.userConnected = object.userConnected ?? undefined;
    message.calibrationUploaded = (object.calibrationUploaded !== undefined && object.calibrationUploaded !== null)
      ? CalibrationUploadedEvent.fromPartial(object.calibrationUploaded)
      : undefined;
    return message;
  },
};

function createBasePhotonTarget(): PhotonTarget {
  return {
    yaw: 0,
    pitch: 0,
    skew: 0,
    area: 0,
    ambiguity: 0,
    fiducialId: 0,
    confidence: 0,
    classId: 0,
    pose: undefined,
  };
}

export const PhotonTarget: MessageFns<PhotonTarget> = {
  encode(message: PhotonTarget, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.yaw !== 0) {
      writer.uint32(9).double(message.yaw);
    }
    if (message.pitch !== 0) {
      writer.uint32(17).double(message.pitch);
    }
    if (message.skew !== 0) {
      writer.uint32(25).double(message.skew);
    }
    if (message.area !== 0) {
      writer.uint32(33).double(message.area);
    }
    if (message.ambiguity !== 0) {
      writer.uint32(41).double(message.ambiguity);
    }
    if (message.fiducialId !== 0) {
      writer.uint32(48).int32(message.fiducialId);
    }
    if (message.confidence !== 0) {
      writer.uint32(57).double(message.confidence);
    }
    if (message.classId !== 0) {
      writer.uint32(64).int32(message.classId);
    }
    if (message.pose !== undefined) {
      ProtobufTransform3d.encode(message.pose, writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PhotonTarget {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePhotonTarget();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 9) {
              break;
            }

            message.yaw = reader.double();
            continue;
          }
          case 2: {
            if (tag !== 17) {
              break;
            }

            message.pitch = reader.double();
            continue;
          }
          case 3: {
            if (tag !== 25) {
              break;
            }

            message.skew = reader.double();
            continue;
          }
          case 4: {
            if (tag !== 33) {
              break;
            }

            message.area = reader.double();
            continue;
          }
          case 5: {
            if (tag !== 41) {
              break;
            }

            message.ambiguity = reader.double();
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.fiducialId = reader.int32();
            continue;
          }
          case 7: {
            if (tag !== 57) {
              break;
            }

            message.confidence = reader.double();
            continue;
          }
          case 8: {
            if (tag !== 64) {
              break;
            }

            message.classId = reader.int32();
            continue;
          }
          case 9: {
            if (tag !== 74) {
              break;
            }

            message.pose = ProtobufTransform3d.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): PhotonTarget {
    return {
      yaw: isSet(object.yaw) ? globalThis.Number(object.yaw) : 0,
      pitch: isSet(object.pitch) ? globalThis.Number(object.pitch) : 0,
      skew: isSet(object.skew) ? globalThis.Number(object.skew) : 0,
      area: isSet(object.area) ? globalThis.Number(object.area) : 0,
      ambiguity: isSet(object.ambiguity) ? globalThis.Number(object.ambiguity) : 0,
      fiducialId: isSet(object.fiducialId) ? globalThis.Number(object.fiducialId) : 0,
      confidence: isSet(object.confidence) ? globalThis.Number(object.confidence) : 0,
      classId: isSet(object.classId) ? globalThis.Number(object.classId) : 0,
      pose: isSet(object.pose) ? ProtobufTransform3d.fromJSON(object.pose) : undefined,
    };
  },

  toJSON(message: PhotonTarget): unknown {
    const obj: any = {};
    if (message.yaw !== 0) {
      obj.yaw = message.yaw;
    }
    if (message.pitch !== 0) {
      obj.pitch = message.pitch;
    }
    if (message.skew !== 0) {
      obj.skew = message.skew;
    }
    if (message.area !== 0) {
      obj.area = message.area;
    }
    if (message.ambiguity !== 0) {
      obj.ambiguity = message.ambiguity;
    }
    if (message.fiducialId !== 0) {
      obj.fiducialId = Math.round(message.fiducialId);
    }
    if (message.confidence !== 0) {
      obj.confidence = message.confidence;
    }
    if (message.classId !== 0) {
      obj.classId = Math.round(message.classId);
    }
    if (message.pose !== undefined) {
      obj.pose = ProtobufTransform3d.toJSON(message.pose);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PhotonTarget>, I>>(base?: I): PhotonTarget {
    return PhotonTarget.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PhotonTarget>, I>>(object: I): PhotonTarget {
    const message = createBasePhotonTarget();
    message.yaw = object.yaw ?? 0;
    message.pitch = object.pitch ?? 0;
    message.skew = object.skew ?? 0;
    message.area = object.area ?? 0;
    message.ambiguity = object.ambiguity ?? 0;
    message.fiducialId = object.fiducialId ?? 0;
    message.confidence = object.confidence ?? 0;
    message.classId = object.classId ?? 0;
    message.pose = (object.pose !== undefined && object.pose !== null)
      ? ProtobufTransform3d.fromPartial(object.pose)
      : undefined;
    return message;
  },
};

function createBaseMultitagResult(): MultitagResult {
  return { bestTransform: undefined, bestReprojectionError: 0, fiducialIDsUsed: [] };
}

export const MultitagResult: MessageFns<MultitagResult> = {
  encode(message: MultitagResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bestTransform !== undefined) {
      ProtobufTransform3d.encode(message.bestTransform, writer.uint32(10).fork()).join();
    }
    if (message.bestReprojectionError !== 0) {
      writer.uint32(17).double(message.bestReprojectionError);
    }
    writer.uint32(26).fork();
    for (const v of message.fiducialIDsUsed) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MultitagResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMultitagResult();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.bestTransform = ProtobufTransform3d.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 17) {
              break;
            }

            message.bestReprojectionError = reader.double();
            continue;
          }
          case 3: {
            if (tag === 24) {
              message.fiducialIDsUsed.push(reader.int32());

              continue;
            }

            if (tag === 26) {
              const end2 = reader.uint32() + reader.pos;
              while (reader.pos < end2) {
                message.fiducialIDsUsed.push(reader.int32());
              }

              continue;
            }

            break;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MultitagResult {
    return {
      bestTransform: isSet(object.bestTransform) ? ProtobufTransform3d.fromJSON(object.bestTransform) : undefined,
      bestReprojectionError: isSet(object.bestReprojectionError) ? globalThis.Number(object.bestReprojectionError) : 0,
      fiducialIDsUsed: globalThis.Array.isArray(object?.fiducialIDsUsed)
        ? object.fiducialIDsUsed.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: MultitagResult): unknown {
    const obj: any = {};
    if (message.bestTransform !== undefined) {
      obj.bestTransform = ProtobufTransform3d.toJSON(message.bestTransform);
    }
    if (message.bestReprojectionError !== 0) {
      obj.bestReprojectionError = message.bestReprojectionError;
    }
    if (message.fiducialIDsUsed?.length) {
      obj.fiducialIDsUsed = message.fiducialIDsUsed.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MultitagResult>, I>>(base?: I): MultitagResult {
    return MultitagResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MultitagResult>, I>>(object: I): MultitagResult {
    const message = createBaseMultitagResult();
    message.bestTransform = (object.bestTransform !== undefined && object.bestTransform !== null)
      ? ProtobufTransform3d.fromPartial(object.bestTransform)
      : undefined;
    message.bestReprojectionError = object.bestReprojectionError ?? 0;
    message.fiducialIDsUsed = object.fiducialIDsUsed?.map((e) => e) || [];
    return message;
  },
};

function createBasePipelineResult(): PipelineResult {
  return {
    cameraUniqueName: "",
    sequenceID: 0,
    fps: 0,
    latency: 0,
    focus: undefined,
    targets: [],
    multitagResult: undefined,
    classNames: [],
  };
}

export const PipelineResult: MessageFns<PipelineResult> = {
  encode(message: PipelineResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cameraUniqueName !== "") {
      writer.uint32(10).string(message.cameraUniqueName);
    }
    if (message.sequenceID !== 0) {
      writer.uint32(16).int64(message.sequenceID);
    }
    if (message.fps !== 0) {
      writer.uint32(25).double(message.fps);
    }
    if (message.latency !== 0) {
      writer.uint32(33).double(message.latency);
    }
    if (message.focus !== undefined) {
      writer.uint32(41).double(message.focus);
    }
    for (const v of message.targets) {
      PhotonTarget.encode(v!, writer.uint32(50).fork()).join();
    }
    if (message.multitagResult !== undefined) {
      MultitagResult.encode(message.multitagResult, writer.uint32(58).fork()).join();
    }
    for (const v of message.classNames) {
      writer.uint32(66).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PipelineResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePipelineResult();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.cameraUniqueName = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.sequenceID = longToNumber(reader.int64());
            continue;
          }
          case 3: {
            if (tag !== 25) {
              break;
            }

            message.fps = reader.double();
            continue;
          }
          case 4: {
            if (tag !== 33) {
              break;
            }

            message.latency = reader.double();
            continue;
          }
          case 5: {
            if (tag !== 41) {
              break;
            }

            message.focus = reader.double();
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.targets.push(PhotonTarget.decode(reader, reader.uint32()));
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.multitagResult = MultitagResult.decode(reader, reader.uint32());
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.classNames.push(reader.string());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): PipelineResult {
    return {
      cameraUniqueName: isSet(object.cameraUniqueName) ? globalThis.String(object.cameraUniqueName) : "",
      sequenceID: isSet(object.sequenceID) ? globalThis.Number(object.sequenceID) : 0,
      fps: isSet(object.fps) ? globalThis.Number(object.fps) : 0,
      latency: isSet(object.latency) ? globalThis.Number(object.latency) : 0,
      focus: isSet(object.focus) ? globalThis.Number(object.focus) : undefined,
      targets: globalThis.Array.isArray(object?.targets)
        ? object.targets.map((e: any) => PhotonTarget.fromJSON(e))
        : [],
      multitagResult: isSet(object.multitagResult) ? MultitagResult.fromJSON(object.multitagResult) : undefined,
      classNames: globalThis.Array.isArray(object?.classNames)
        ? object.classNames.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: PipelineResult): unknown {
    const obj: any = {};
    if (message.cameraUniqueName !== "") {
      obj.cameraUniqueName = message.cameraUniqueName;
    }
    if (message.sequenceID !== 0) {
      obj.sequenceID = Math.round(message.sequenceID);
    }
    if (message.fps !== 0) {
      obj.fps = message.fps;
    }
    if (message.latency !== 0) {
      obj.latency = message.latency;
    }
    if (message.focus !== undefined) {
      obj.focus = message.focus;
    }
    if (message.targets?.length) {
      obj.targets = message.targets.map((e) => PhotonTarget.toJSON(e));
    }
    if (message.multitagResult !== undefined) {
      obj.multitagResult = MultitagResult.toJSON(message.multitagResult);
    }
    if (message.classNames?.length) {
      obj.classNames = message.classNames;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PipelineResult>, I>>(base?: I): PipelineResult {
    return PipelineResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PipelineResult>, I>>(object: I): PipelineResult {
    const message = createBasePipelineResult();
    message.cameraUniqueName = object.cameraUniqueName ?? "";
    message.sequenceID = object.sequenceID ?? 0;
    message.fps = object.fps ?? 0;
    message.latency = object.latency ?? 0;
    message.focus = object.focus ?? undefined;
    message.targets = object.targets?.map((e) => PhotonTarget.fromPartial(e)) || [];
    message.multitagResult = (object.multitagResult !== undefined && object.multitagResult !== null)
      ? MultitagResult.fromPartial(object.multitagResult)
      : undefined;
    message.classNames = object.classNames?.map((e) => e) || [];
    return message;
  },
};

function createBaseUiMetrics(): UiMetrics {
  return {};
}

export const UiMetrics: MessageFns<UiMetrics> = {
  encode(_: UiMetrics, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UiMetrics {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseUiMetrics();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): UiMetrics {
    return {};
  },

  toJSON(_: UiMetrics): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<UiMetrics>, I>>(base?: I): UiMetrics {
    return UiMetrics.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UiMetrics>, I>>(_: I): UiMetrics {
    const message = createBaseUiMetrics();
    return message;
  },
};

function createBaseLogMessage(): LogMessage {
  return {};
}

export const LogMessage: MessageFns<LogMessage> = {
  encode(_: LogMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseLogMessage();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): LogMessage {
    return {};
  },

  toJSON(_: LogMessage): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<LogMessage>, I>>(base?: I): LogMessage {
    return LogMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogMessage>, I>>(_: I): LogMessage {
    const message = createBaseLogMessage();
    return message;
  },
};

function createBaseUiCalibrationData(): UiCalibrationData {
  return {};
}

export const UiCalibrationData: MessageFns<UiCalibrationData> = {
  encode(_: UiCalibrationData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UiCalibrationData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseUiCalibrationData();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): UiCalibrationData {
    return {};
  },

  toJSON(_: UiCalibrationData): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<UiCalibrationData>, I>>(base?: I): UiCalibrationData {
    return UiCalibrationData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UiCalibrationData>, I>>(_: I): UiCalibrationData {
    const message = createBaseUiCalibrationData();
    return message;
  },
};

function createBaseVisionSourceManagerState(): VisionSourceManagerState {
  return {};
}

export const VisionSourceManagerState: MessageFns<VisionSourceManagerState> = {
  encode(_: VisionSourceManagerState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VisionSourceManagerState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseVisionSourceManagerState();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): VisionSourceManagerState {
    return {};
  },

  toJSON(_: VisionSourceManagerState): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<VisionSourceManagerState>, I>>(base?: I): VisionSourceManagerState {
    return VisionSourceManagerState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VisionSourceManagerState>, I>>(_: I): VisionSourceManagerState {
    const message = createBaseVisionSourceManagerState();
    return message;
  },
};

function createBaseMutatePipelineSettings(): MutatePipelineSettings {
  return {};
}

export const MutatePipelineSettings: MessageFns<MutatePipelineSettings> = {
  encode(_: MutatePipelineSettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MutatePipelineSettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMutatePipelineSettings();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): MutatePipelineSettings {
    return {};
  },

  toJSON(_: MutatePipelineSettings): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MutatePipelineSettings>, I>>(base?: I): MutatePipelineSettings {
    return MutatePipelineSettings.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MutatePipelineSettings>, I>>(_: I): MutatePipelineSettings {
    const message = createBaseMutatePipelineSettings();
    return message;
  },
};

function createBasePhotonSettings(): PhotonSettings {
  return {};
}

export const PhotonSettings: MessageFns<PhotonSettings> = {
  encode(_: PhotonSettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PhotonSettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePhotonSettings();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): PhotonSettings {
    return {};
  },

  toJSON(_: PhotonSettings): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<PhotonSettings>, I>>(base?: I): PhotonSettings {
    return PhotonSettings.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PhotonSettings>, I>>(_: I): PhotonSettings {
    const message = createBasePhotonSettings();
    return message;
  },
};

function createBaseCameraSettings(): CameraSettings {
  return {
    nickname: "",
    uniqueName: "",
    inputStreamPort: 0,
    outputStreamPort: 0,
    isEnabled: false,
    isConnected: false,
    hasConnected: false,
    mismatch: false,
  };
}

export const CameraSettings: MessageFns<CameraSettings> = {
  encode(message: CameraSettings, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nickname !== "") {
      writer.uint32(10).string(message.nickname);
    }
    if (message.uniqueName !== "") {
      writer.uint32(18).string(message.uniqueName);
    }
    if (message.inputStreamPort !== 0) {
      writer.uint32(24).int32(message.inputStreamPort);
    }
    if (message.outputStreamPort !== 0) {
      writer.uint32(32).int32(message.outputStreamPort);
    }
    if (message.isEnabled !== false) {
      writer.uint32(40).bool(message.isEnabled);
    }
    if (message.isConnected !== false) {
      writer.uint32(48).bool(message.isConnected);
    }
    if (message.hasConnected !== false) {
      writer.uint32(56).bool(message.hasConnected);
    }
    if (message.mismatch !== false) {
      writer.uint32(64).bool(message.mismatch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CameraSettings {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCameraSettings();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.nickname = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.uniqueName = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.inputStreamPort = reader.int32();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.outputStreamPort = reader.int32();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.isEnabled = reader.bool();
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.isConnected = reader.bool();
            continue;
          }
          case 7: {
            if (tag !== 56) {
              break;
            }

            message.hasConnected = reader.bool();
            continue;
          }
          case 8: {
            if (tag !== 64) {
              break;
            }

            message.mismatch = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): CameraSettings {
    return {
      nickname: isSet(object.nickname) ? globalThis.String(object.nickname) : "",
      uniqueName: isSet(object.uniqueName) ? globalThis.String(object.uniqueName) : "",
      inputStreamPort: isSet(object.inputStreamPort) ? globalThis.Number(object.inputStreamPort) : 0,
      outputStreamPort: isSet(object.outputStreamPort) ? globalThis.Number(object.outputStreamPort) : 0,
      isEnabled: isSet(object.isEnabled) ? globalThis.Boolean(object.isEnabled) : false,
      isConnected: isSet(object.isConnected) ? globalThis.Boolean(object.isConnected) : false,
      hasConnected: isSet(object.hasConnected) ? globalThis.Boolean(object.hasConnected) : false,
      mismatch: isSet(object.mismatch) ? globalThis.Boolean(object.mismatch) : false,
    };
  },

  toJSON(message: CameraSettings): unknown {
    const obj: any = {};
    if (message.nickname !== "") {
      obj.nickname = message.nickname;
    }
    if (message.uniqueName !== "") {
      obj.uniqueName = message.uniqueName;
    }
    if (message.inputStreamPort !== 0) {
      obj.inputStreamPort = Math.round(message.inputStreamPort);
    }
    if (message.outputStreamPort !== 0) {
      obj.outputStreamPort = Math.round(message.outputStreamPort);
    }
    if (message.isEnabled !== false) {
      obj.isEnabled = message.isEnabled;
    }
    if (message.isConnected !== false) {
      obj.isConnected = message.isConnected;
    }
    if (message.hasConnected !== false) {
      obj.hasConnected = message.hasConnected;
    }
    if (message.mismatch !== false) {
      obj.mismatch = message.mismatch;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CameraSettings>, I>>(base?: I): CameraSettings {
    return CameraSettings.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CameraSettings>, I>>(object: I): CameraSettings {
    const message = createBaseCameraSettings();
    message.nickname = object.nickname ?? "";
    message.uniqueName = object.uniqueName ?? "";
    message.inputStreamPort = object.inputStreamPort ?? 0;
    message.outputStreamPort = object.outputStreamPort ?? 0;
    message.isEnabled = object.isEnabled ?? false;
    message.isConnected = object.isConnected ?? false;
    message.hasConnected = object.hasConnected ?? false;
    message.mismatch = object.mismatch ?? false;
    return message;
  },
};

function createBaseOutgoingDashboardEvent(): OutgoingDashboardEvent {
  return {
    settings: undefined,
    cameraSettings: [],
    updatePipelineResult: undefined,
    metrics: undefined,
    log: undefined,
    calibrationData: undefined,
    visionSourceManager: undefined,
    mutatePipeline: undefined,
  };
}

export const OutgoingDashboardEvent: MessageFns<OutgoingDashboardEvent> = {
  encode(message: OutgoingDashboardEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.settings !== undefined) {
      PhotonSettings.encode(message.settings, writer.uint32(10).fork()).join();
    }
    for (const v of message.cameraSettings) {
      CameraSettings.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.updatePipelineResult !== undefined) {
      PipelineResult.encode(message.updatePipelineResult, writer.uint32(26).fork()).join();
    }
    if (message.metrics !== undefined) {
      UiMetrics.encode(message.metrics, writer.uint32(34).fork()).join();
    }
    if (message.log !== undefined) {
      LogMessage.encode(message.log, writer.uint32(42).fork()).join();
    }
    if (message.calibrationData !== undefined) {
      UiCalibrationData.encode(message.calibrationData, writer.uint32(50).fork()).join();
    }
    if (message.visionSourceManager !== undefined) {
      VisionSourceManagerState.encode(message.visionSourceManager, writer.uint32(58).fork()).join();
    }
    if (message.mutatePipeline !== undefined) {
      MutatePipelineSettings.encode(message.mutatePipeline, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OutgoingDashboardEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseOutgoingDashboardEvent();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.settings = PhotonSettings.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.cameraSettings.push(CameraSettings.decode(reader, reader.uint32()));
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.updatePipelineResult = PipelineResult.decode(reader, reader.uint32());
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.metrics = UiMetrics.decode(reader, reader.uint32());
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.log = LogMessage.decode(reader, reader.uint32());
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.calibrationData = UiCalibrationData.decode(reader, reader.uint32());
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.visionSourceManager = VisionSourceManagerState.decode(reader, reader.uint32());
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.mutatePipeline = MutatePipelineSettings.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): OutgoingDashboardEvent {
    return {
      settings: isSet(object.settings) ? PhotonSettings.fromJSON(object.settings) : undefined,
      cameraSettings: globalThis.Array.isArray(object?.cameraSettings)
        ? object.cameraSettings.map((e: any) => CameraSettings.fromJSON(e))
        : [],
      updatePipelineResult: isSet(object.updatePipelineResult)
        ? PipelineResult.fromJSON(object.updatePipelineResult)
        : undefined,
      metrics: isSet(object.metrics) ? UiMetrics.fromJSON(object.metrics) : undefined,
      log: isSet(object.log) ? LogMessage.fromJSON(object.log) : undefined,
      calibrationData: isSet(object.calibrationData) ? UiCalibrationData.fromJSON(object.calibrationData) : undefined,
      visionSourceManager: isSet(object.visionSourceManager)
        ? VisionSourceManagerState.fromJSON(object.visionSourceManager)
        : undefined,
      mutatePipeline: isSet(object.mutatePipeline) ? MutatePipelineSettings.fromJSON(object.mutatePipeline) : undefined,
    };
  },

  toJSON(message: OutgoingDashboardEvent): unknown {
    const obj: any = {};
    if (message.settings !== undefined) {
      obj.settings = PhotonSettings.toJSON(message.settings);
    }
    if (message.cameraSettings?.length) {
      obj.cameraSettings = message.cameraSettings.map((e) => CameraSettings.toJSON(e));
    }
    if (message.updatePipelineResult !== undefined) {
      obj.updatePipelineResult = PipelineResult.toJSON(message.updatePipelineResult);
    }
    if (message.metrics !== undefined) {
      obj.metrics = UiMetrics.toJSON(message.metrics);
    }
    if (message.log !== undefined) {
      obj.log = LogMessage.toJSON(message.log);
    }
    if (message.calibrationData !== undefined) {
      obj.calibrationData = UiCalibrationData.toJSON(message.calibrationData);
    }
    if (message.visionSourceManager !== undefined) {
      obj.visionSourceManager = VisionSourceManagerState.toJSON(message.visionSourceManager);
    }
    if (message.mutatePipeline !== undefined) {
      obj.mutatePipeline = MutatePipelineSettings.toJSON(message.mutatePipeline);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OutgoingDashboardEvent>, I>>(base?: I): OutgoingDashboardEvent {
    return OutgoingDashboardEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OutgoingDashboardEvent>, I>>(object: I): OutgoingDashboardEvent {
    const message = createBaseOutgoingDashboardEvent();
    message.settings = (object.settings !== undefined && object.settings !== null)
      ? PhotonSettings.fromPartial(object.settings)
      : undefined;
    message.cameraSettings = object.cameraSettings?.map((e) => CameraSettings.fromPartial(e)) || [];
    message.updatePipelineResult = (object.updatePipelineResult !== undefined && object.updatePipelineResult !== null)
      ? PipelineResult.fromPartial(object.updatePipelineResult)
      : undefined;
    message.metrics = (object.metrics !== undefined && object.metrics !== null)
      ? UiMetrics.fromPartial(object.metrics)
      : undefined;
    message.log = (object.log !== undefined && object.log !== null) ? LogMessage.fromPartial(object.log) : undefined;
    message.calibrationData = (object.calibrationData !== undefined && object.calibrationData !== null)
      ? UiCalibrationData.fromPartial(object.calibrationData)
      : undefined;
    message.visionSourceManager = (object.visionSourceManager !== undefined && object.visionSourceManager !== null)
      ? VisionSourceManagerState.fromPartial(object.visionSourceManager)
      : undefined;
    message.mutatePipeline = (object.mutatePipeline !== undefined && object.mutatePipeline !== null)
      ? MutatePipelineSettings.fromPartial(object.mutatePipeline)
      : undefined;
    return message;
  },
};

function createBasePhotonDataChangeEvent(): PhotonDataChangeEvent {
  return { originCtxSessionId: undefined, event: undefined };
}

export const PhotonDataChangeEvent: MessageFns<PhotonDataChangeEvent> = {
  encode(message: PhotonDataChangeEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.originCtxSessionId !== undefined) {
      writer.uint32(10).string(message.originCtxSessionId);
    }
    if (message.event !== undefined) {
      UiChangeEvent.encode(message.event, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PhotonDataChangeEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePhotonDataChangeEvent();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.originCtxSessionId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.event = UiChangeEvent.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): PhotonDataChangeEvent {
    return {
      originCtxSessionId: isSet(object.originCtxSessionId) ? globalThis.String(object.originCtxSessionId) : undefined,
      event: isSet(object.event) ? UiChangeEvent.fromJSON(object.event) : undefined,
    };
  },

  toJSON(message: PhotonDataChangeEvent): unknown {
    const obj: any = {};
    if (message.originCtxSessionId !== undefined) {
      obj.originCtxSessionId = message.originCtxSessionId;
    }
    if (message.event !== undefined) {
      obj.event = UiChangeEvent.toJSON(message.event);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PhotonDataChangeEvent>, I>>(base?: I): PhotonDataChangeEvent {
    return PhotonDataChangeEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PhotonDataChangeEvent>, I>>(object: I): PhotonDataChangeEvent {
    const message = createBasePhotonDataChangeEvent();
    message.originCtxSessionId = object.originCtxSessionId ?? undefined;
    message.event = (object.event !== undefined && object.event !== null)
      ? UiChangeEvent.fromPartial(object.event)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
