/*
 * MIT License
 *
 * Copyright (c) PhotonVision
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// THIS FILE WAS AUTO-GENERATED BY ./photon-serde/generate_messages.py. DO NOT MODIFY

#include "photon/serde/Int64TestMessageSerde.h"


namespace photon {

using StructType = SerdeType<Int64TestMessage>;

void StructType::Pack(Packet& packet, const Int64TestMessage& value) {
  packet.Pack<int64_t>(value.test);
  packet.Pack<std::vector<int64_t>>(value.vlaTest);
  packet.Pack<std::optional<int64_t>>(value.optTest);
}

Int64TestMessage StructType::Unpack(Packet& packet) {
  return Int64TestMessage{ Int64TestMessage_PhotonStruct{
    .test = packet.Unpack<int64_t>(),
    .vlaTest = packet.Unpack<std::vector<int64_t>>(),
    .optTest = packet.Unpack<std::optional<int64_t>>(),
  }};
}

} // namespace photon
