/*
 * MIT License
 *
 * Copyright (c) PhotonVision
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// THIS FILE WAS AUTO-GENERATED BY ./photon-serde/generate_messages.py. DO NOT MODIFY

#include "photon/serde/Transform3dTestMessageSerde.h"


namespace photon {

using StructType = SerdeType<Transform3dTestMessage>;

void StructType::Pack(Packet& packet, const Transform3dTestMessage& value) {
  packet.Pack<wpi::math::Transform3d>(value.test);
  packet.Pack<std::vector<wpi::math::Transform3d>>(value.vlaTest);
  packet.Pack<std::optional<wpi::math::Transform3d>>(value.optTest);
}

Transform3dTestMessage StructType::Unpack(Packet& packet) {
  return Transform3dTestMessage{ Transform3dTestMessage_PhotonStruct{
    .test = packet.Unpack<wpi::math::Transform3d>(),
    .vlaTest = packet.Unpack<std::vector<wpi::math::Transform3d>>(),
    .optTest = packet.Unpack<std::optional<wpi::math::Transform3d>>(),
  }};
}

} // namespace photon
